config/routes.rb
OneGoal::Application.routes.draw do
  

  get 'user/edit' => 'users#edit', :as => :edit_current_user

  get 'signup' => 'users#new', :as => :signup
  
  get 'login' => 'sessions#new', :as => :login
  
  get 'logout' => 'sessions#logout', :as => :logout

  get 'home' => 'sessions#home', :as => :home

  get 'about' => 'sessions#about', :as => :about

  get 'determine_next_step'  => 'sessions#determine_next_step', :as => :determine_next_step

  get 'unauthorized_access' => 'sessions#unauthorized_access', :as => :unauthorized_access

  get 'complete_action_step/:id' => 'action_steps#complete_action_step', :as => :complete_action_step

  get 'pending' => 'web_resources#pending', :as => :pending

  get 'review/:id' => 'web_resources#review', :as => :review

  get 'faq' => 'sessions#faq', :as => :faq

  get 'counts' => 'members#counts', :as => :counts

  get 'public_goals' => 'members#index', :as => :public_goals

  resources :sessions
  resources :users
  resources :goals 
  resources :action_steps
  resources :members 
  resources :system_texts
  resources :web_resources
  resources :password_resets

  root 'sessions#new'

end

app/models/action_step.rb
# == Schema Information
#
# Table name: action_steps
#
#  id          :integer          not null, primary key
#  description :string(255)
#  target_date :date
#  completed   :date
#  created_at  :datetime
#  updated_at  :datetime
#  goal_id     :integer
#

require 'pp'

class ActionStep < ActiveRecord::Base

  paginates_per 5

  validate :target_date_format , :completed_date_format 

  validates_presence_of :description, :target_date

  def target_date_format
    begin
      #self['target_date'] =  
      @attributes['target_date'].to_s
    rescue Exception => e
      errors.add :target_date, ":  Must be entered in mm/dd/yyyy format'.  " 
    end
  end

  def completed_date_format
    begin
      if @attributes['completed'].nil? == false
        #self['completed'] = 
        @attributes['completed'].to_s
      end
    rescue Exception => e
      errors.add :completed_date, ":  Must be entered in mm/dd/yyyy format'.  " 
    end
  end


  def to_h
    {
      :id => id,
      :description => description,
      :target_date => target_date,
      :completed => completed,
      :goal_id => goal_id 
    }
  end


end

app/controllers/action_steps_controller.rb
require 'pp'

class ActionStepsController < ApplicationController



  before_action :set_action_step, only: [:show, :edit, :update, :destroy]

  before_filter :check_for_member





  def check_for_member
    if Member.where("user_id = ? ", session['user_id']).count == 0
      redirect_to new_member_path, :notice => SystemText.text_for_key('MEMBER_INFO_REQUIRED_BEFORE_GOAL')
    end
    if Member.where("user_id = ? ", session['user_id']).count == 1 && Goal.where("user_id = ? ", session['user_id']).count == 0
      redirect_to new_goal_path, :notice =>  SystemText.text_for_key('GOAL_INFO_REQUIRED_BEFORE_ACTION_STEPS')
    end
  end



  # GET /action_steps
  # GET /action_steps.json
  def index
    @action_steps = ActionStep.where("goal_id = ?", Goal.where("user_id = ? ", session['user_id'].to_i).first.id).order("target_date ASC").page params[:page]
  end

  # GET /action_steps/1
  # GET /action_steps/1.json
  def show
  end

  # GET /action_steps/new
  def new
    @action_step = ActionStep.new
  end

  # GET /action_steps/1/edit
  def edit
  end

  # POST /action_steps
  # POST /action_steps.json
  def create
    @action_step = ActionStep.new(action_step_params)
    @action_step.goal_id = Goal.where("user_id =? ", session['user_id'].to_i).first.id
    respond_to do |format|
      if @action_step.save
        format.html { redirect_to action_steps_path, notice: 'Action step was successfully created.' }
        format.json { render action: 'show', status: :created, location: @action_step }
      else
        format.html { render action: 'new' }
        format.json { render json: @action_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_steps/1
  # PATCH/PUT /action_steps/1.json
  def update
    respond_to do |format|
      if @action_step.update(action_step_params)
        format.html { redirect_to action_steps_path, notice: 'Action step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @action_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_steps/1
  # DELETE /action_steps/1.json
  def destroy
    @action_step.destroy
    respond_to do |format|
      format.html { redirect_to action_steps_url }
      format.json { head :no_content }
    end
  end


  def complete_action_step
    step = ActionStep.find(params['id'].to_i)
    step.completed = Date.today.to_s
    step.save
    redirect_to action_steps_path
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_step
      @action_step = ActionStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_step_params
      params.require(:action_step).permit(:goal_id, :description, :target_date, :completed)
    end
end

app/helpers/action_steps_helper.rb
module ActionStepsHelper
end

app/views/action_steps/_form.html.erb
<%= form_for(@action_step) do |f| %>
  <% if @action_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_step.errors.count, "error") %> prohibited this action_step from being saved:</h2>

      <ul>
      <% @action_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description , :size => 100%>
  </div>

  <div class="field">
    <label>Target Date <span style='font-size:10pt;color:gray'>(Please enter as MM/DD/YYYY)</span></label>
    <%= f.text_field :target_date   , :value => (@action_step.target_date.blank? ? '' : @action_step.target_date.to_s) %>    
  </div>
  
  <div class="field">
    <label>Date Completed <span style='font-size:10pt;color:gray'>(Please enter as MM/DD/YYYY)</span></label>
    <%= f.text_field :completed   , :value => (@action_step.completed.blank? ? '' : @action_step.completed.to_s) %>  
  </div>
  <div class="actions">
    <%= f.submit  "Save Action Step" %>
  </div>
<% end %>

app/views/action_steps/edit.html.erb
<h1>Editing action_step</h1>


<%= render 'form' %>

<%= link_to 'Show', @action_step %> |
<%= link_to 'Back', action_steps_path %>

app/views/action_steps/index.html.erb
<h1>Your ONE Goal Action Steps</h1>

<% if notice %>
  <div style='margin-left:30px;font-size:12pt;height:25px;border-radius:3px;width:400px;background-color:green;color:white;text-align:center;' id="notice">
     <div><%= notice %>   </div>
  </div>
<% end %>


<table style='
      font-size:12px;
      margin-left:30px;
      width:90%;
      border:2px solid;
      border-color:#800000'>

  <thead>
    <tr><td colspan=6 style='height:20px;font-size:14pt;background-color:maroon;color:white;text-align:center'>You have completed <%= Goal.percent_complete(User.find(session['user_id'].to_i)) %>% of the steps toward your goal.</td></tr>
    <tr><td colspan=6>&nbsp;</td></tr>
    <tr><td colspan=6 style='text-align:right;font-size:12pt'><%= link_to 'Enter New Action Step', new_action_step_path %></td></tr>
    <tr><td colspan=6>&nbsp;</td></tr>
    <tr>
      <th>Description</th>
      <th>Target Date</th>
      <th>Date Completed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @action_steps.each do |action_step| %>
      <tr>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_ITEM_FONT_SIZE')%>px' ><%= action_step.description %></td>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_TARGET_DATE_FONT_SIZE')%>px' ><%= action_step.target_date %></td>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_COMPLETED_DATE_FONT_SIZE')%>px' ><%= action_step.completed %></td>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_LINKS_FONT_SIZE')%>px' ><%= link_to 'Edit', edit_action_step_path(action_step) %></td>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_LINKS_FONT_SIZE')%>px' ><%= link_to 'Complete', complete_action_step_path(action_step), method: :get, data: { confirm: 'Complete Action Step?' } %></td>
        <td style='font-size:<%=SystemText.text_for_key('ACTION_STEP_LINKS_FONT_SIZE')%>px' ><%= link_to 'Delete', action_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @action_steps %>

app/views/action_steps/new.html.erb
<h1><%=raw SystemText.text_for_key('ACTION_STEP_PAGE_HEADER') %></h1>

<%= render 'form' %>

<%= link_to 'Back', action_steps_path %>

app/views/action_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @action_step.goal_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_step.description %>
</p>

<p>
  <strong>Target date:</strong>
  <%= @action_step.target_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @action_step.completed %>
</p>

<%= link_to 'Edit', edit_action_step_path(@action_step) %> |
<%= link_to 'Back', action_steps_path %>