config/routes.rb
OneGoal::Application.routes.draw do
  

  get 'user/edit' => 'users#edit', :as => :edit_current_user

  get 'signup' => 'users#new', :as => :signup
  
  get 'login' => 'sessions#new', :as => :login
  
  get 'logout' => 'sessions#logout', :as => :logout

  get 'home' => 'sessions#home', :as => :home

  get 'about' => 'sessions#about', :as => :about

  get 'determine_next_step'  => 'sessions#determine_next_step', :as => :determine_next_step

  get 'unauthorized_access' => 'sessions#unauthorized_access', :as => :unauthorized_access

  get 'complete_action_step/:id' => 'action_steps#complete_action_step', :as => :complete_action_step

  get 'pending' => 'web_resources#pending', :as => :pending

  get 'review/:id' => 'web_resources#review', :as => :review

  get 'faq' => 'sessions#faq', :as => :faq

  get 'counts' => 'members#counts', :as => :counts

  get 'public_goals' => 'members#index', :as => :public_goals

  resources :sessions
  resources :users
  resources :goals 
  resources :action_steps
  resources :members 
  resources :system_texts
  resources :web_resources
  resources :password_resets

  root 'sessions#new'

end

app/models/system_text.rb
# == Schema Information
#
# Table name: system_texts
#
#  id          :integer          not null, primary key
#  key         :string(255)
#  value       :text
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#

class SystemText < ActiveRecord::Base

  paginates_per 8


  validates_presence_of :key, :value, :description

  def self.text_for_key key 
    result  = SystemText.where("key = ?",key).first 
    if result.nil?
      "No System Text defined for key '#{key}'"
    else
      result.value
    end
  end

  def to_h
    {
      :id => id,
      :description => description,
      :key => key,
      :value => value
    }
  end

end

app/controllers/system_texts_controller.rb
class SystemTextsController < ApplicationController
  before_action :set_system_text, only: [:show, :edit, :update, :destroy]

  before_filter :check_for_admin






  # GET /system_texts
  # GET /system_texts.json
  def index
    @system_texts = SystemText.order(:key).page params[:page]
  end

  # GET /system_texts/1
  # GET /system_texts/1.json
  def show
  end

  # GET /system_texts/new
  def new
    @system_text = SystemText.new
  end

  # GET /system_texts/1/edit
  def edit
  end

  # POST /system_texts
  # POST /system_texts.json
  def create
    @system_text = SystemText.new(system_text_params)

    respond_to do |format|
      if @system_text.save
        format.html { redirect_to system_texts_path, notice: 'System text was successfully created.' }
        format.json { render action: 'show', status: :created, location: @system_text }
      else
        format.html { render action: 'new' }
        format.json { render json: @system_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_texts/1
  # PATCH/PUT /system_texts/1.json
  def update
    respond_to do |format|
      if @system_text.update(system_text_params)
        format.html { redirect_to system_texts_path, notice: 'System text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @system_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_texts/1
  # DELETE /system_texts/1.json
  def destroy
    @system_text.destroy
    respond_to do |format|
      format.html { redirect_to system_texts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_text
      @system_text = SystemText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_text_params
      params.require(:system_text).permit(:key, :value, :description)
    end



end

app/helpers/system_texts_helper.rb
module SystemTextsHelper
end

app/views/system_texts/_form.html.erb
<%= form_for(@system_text) do |f| %>
  <% if @system_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system_text.errors.count, "error") %> prohibited this system_text from being saved:</h2>

      <ul>
      <% @system_text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/system_texts/edit.html.erb
<h1>Editing System Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_text %> |
<%= link_to 'Back', system_texts_path %>

app/views/system_texts/index.html.erb
<h1>Configure Text for ONE Goal</h1>
<h4>Access to this page limited to administrators</h4>


<% if notice %>
  <div style=';margin-left:30px; ;font-size:12pt;height:25px;border-radius:3px;width:400px;background-color:green;color:white;text-align:center;' id="notice">
     <div><%= notice %>   </div>
  </div>
<% end %>


<table <table style='
      font-size:12px;
      margin-left:30px;
      width:90%;
      border:2px solid;
      border-color:#800000'>
  <thead>
      <tr><td colspan=6   style='text-align:right;'><%= link_to 'New System Text Entry', new_system_text_path %></td></tr>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Last Modified</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @system_texts.each do |system_text| %>
      <tr>
        <td><%= (system_text.key.length > 30) ? "#{system_text.key.slice(0,30)}..." : system_text.key %></td>
        <td><%= "#{system_text.value.slice(0,50)}..." %></td>
        <td><%= system_text.updated_at.localtime.strftime("%m/%d/%Y %I:%M %p") %></td>
        <td><%= link_to 'Show', system_text %></td>
        <td><%= link_to 'Edit', edit_system_text_path(system_text) %></td>
        <td><%= link_to 'Delete', system_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @system_texts %>

app/views/system_texts/new.html.erb
<h1>New System Text</h1>

<%= render 'form' %>

<%= link_to 'Back', system_texts_path %>

app/views/system_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @system_text.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @system_text.value %>
</p>


<p>
  <strong>Value:</strong>
  <%= @system_text.description	 %>
</p>


<%= link_to 'Edit', edit_system_text_path(@system_text) %> |
<%= link_to 'Back', system_texts_path %>