config/routes.rb
OneGoal::Application.routes.draw do
  

  get 'user/edit' => 'users#edit', :as => :edit_current_user

  get 'signup' => 'users#new', :as => :signup
  
  get 'login' => 'sessions#new', :as => :login
  
  get 'logout' => 'sessions#logout', :as => :logout

  get 'home' => 'sessions#home', :as => :home

  get 'about' => 'sessions#about', :as => :about

  get 'determine_next_step'  => 'sessions#determine_next_step', :as => :determine_next_step

  get 'unauthorized_access' => 'sessions#unauthorized_access', :as => :unauthorized_access

  get 'complete_action_step/:id' => 'action_steps#complete_action_step', :as => :complete_action_step

  get 'pending' => 'web_resources#pending', :as => :pending

  get 'review/:id' => 'web_resources#review', :as => :review

  get 'faq' => 'sessions#faq', :as => :faq

  get 'counts' => 'members#counts', :as => :counts

  get 'public_goals' => 'members#index', :as => :public_goals

  resources :sessions
  resources :users
  resources :goals 
  resources :action_steps
  resources :members 
  resources :system_texts
  resources :web_resources
  resources :password_resets

  root 'sessions#new'

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  note        :text
#

class Goal < ActiveRecord::Base


  validates_presence_of :description

  def self.for_user user 
    id = (user.class == User) ? user.id : user
    goal = Goal.find_by_user_id(id)
    goal.nil? ? Goal.new : goal
  end



  def self.entered_for_user? user 
    id = (user.class == User) ? user.id : user
    Goal.where("user_id = ?", id).length > 0 
  end
  
  def self.percent_complete user
    id = (user.class == User) ? user.id : user
    goal = Goal.find_by_user_id(id)
    return 0.0 if goal.nil?
    return 0.0 if ActionStep.where("goal_id = ?", goal.id).count == 0
    total = ActionStep.where("goal_id = ?", goal.id).count * 1.0
    completed = ActionStep.where("goal_id = ? and completed is not NULL", goal.id).count * 1.0
    puts total
    puts completed
    return   (100 * (completed / total)).round(2).to_s
  end


  def self.marquee_text

    marquee_goals = Array.new 
    goals = Goal.all.each do |goal|
      x = {}
      x[:goal] = goal.description
      user = User.find(goal.user_id)
      member = Member.where("user_id = ?", user.id).first
      marquee_goals << "#{member.display_name} : '#{goal.description}' #{Goal.percent_complete(user)}% complete." 
    end 

    marquee_goals.join("....    ")


  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]


  before_filter :check_for_member




  def check_for_member
    if Member.where("user_id = ? ", session['user_id']).count == 0
      redirect_to new_member_path, :notice => SystemText.text_for_key('MEMBER_INFO_REQUIRED_BEFORE_GOAL')
    end
  end

  
  # GET /goals
  # GET /goals.json
  def index
    @goals = []
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.where("user_id = ?", session[:user_id].to_i).first
    @goal = Goal.new if @goal.nil?  
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create

    @goal = Goal.new(goal_params)
    @goal.user_id = session['user_id'].to_i


    respond_to do |format|
      if @goal.save
        format.html { redirect_to new_goal_path, notice: 'Goal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @goal }
      else
        format.html { render action: 'new' }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to new_goal_path, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:user_id, :description, :note)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<% if notice %>
  <div style='margin-left:30px;margin-bottom:10px;font-size:12pt;height:25px;border-radius:3px;width:400px;background-color:green;color:white;text-align:center;' id="notice">
     <div><%= notice %>   </div>
  </div>
<% end %>


<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div style='margin-bottom:20px'>
    <div>
        <div style='font-size:18px; height:50px; margin-left:20px; border-top-left-radius:10px; border-top-right-radius:10px; width:400px; background-color:maroon; color:white; margin-left:30px; float-left; '> 
          <br/>
            <span style='margin-top:10px;margin-left:120px'>
              My ONE Goal
            </span>
        </div>


        <div style='font-size:18px; margin-left:30px; width:600px; height:300px; border-bottom-left-radius:10px; border-bottom-right-radius:10px; border-top-right-radius:10px; border:2px solid; border-color:#800000; float:left '>
          <br/>
          <div style='margin-left:27px;margin-top:20px'>
              <%= f.text_area :description,  :rows => 3, :cols => 10 %>
          </div>
          <p style='margin-left:30px; margin-top:-7px'><%=raw SystemText.text_for_key('GOAL_DESCRIPTION') %></p><br>


          <div style='margin-left:27px;margin-top:20px'>
            <%= f.text_area :note,  :rows => 3, :cols => 10 %>
          </div>
          <p style='margin-left:30px; margin-top:-7px'><%=raw SystemText.text_for_key('GOAL_NOTE_DESCRIPTION') %></p><br>
        </div>
      

    </div>
    
  </div>

  <div style='clear:both;padding-top:20px' >
    
    <div style='margin-top:40px;margin-left:30px' >
      <%= f.submit "Save Goal" %>
    </div>
  
  </div>



<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Display name</th>
      <th>Club name</th>
      <th>Display club</th>
      <th>Request buddy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.user_id %></td>
        <td><%= goal.description %></td>
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<%= render 'form' %>

 

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>



<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>